### ISSUE TITLE
Sample in ASP MVC

### ISSUE THREAD

**Issue by papyr** [KingKnecht/FlatStreamToHierarchy#5]
Hi can you help with the same in ASP MVC 5 please.

thanks

**Comment by KingKnecht** [comment]
Hi, not sure what you mean exactly. This some demo code about 
[DynamicData](https://github.com/RolandPheasant/FlatStreamToHierarchy) library.
DynamicData lets you listen to a stream of events (data packages) (buzzwords: Observables, RX,  Reactive). The problem is now how to convert a flat stream into a hierarchical data structure if ParentId is given for each data package. If you want to know how this is done with the DynamicData library you can investigate my demo. If you want to know what tech is behind the functions I'm using to get this done you should investigate the DynamicData source code. Sorry, I don't have better answer for you.

**Comment by KingKnecht** [comment]
Maybe you mean the GUI stuff? The display of the tree? In the WPF demo I'm using a TreeView control. Pretty sure there is something similar in HTML. And with some Javascript/CSS voodoo - which I don't know - you can achieve the same result. Shouldn't be that hard and you should find many examples about a cool looking tree in HTML/CSS.
